SIZE_MAP = 

{
  "Bold"=>
    [/\[b(:.*)?\](.*?)\[\/b\1?\]/mi,
      "<B><s>[b]</s>\\2<e>[/b]</e></B>",
      "Embolden text",
      "Look [b]here[/b]",
      :bold],
  "Italics"=>
    [/\[i(:.+)?\](.*?)\[\/i\1?\]/mi,
      "<I><s>[i]</s>\\2<e>[/i]</e></I>",
      "Italicize or emphasize text",
      "Even my [i]cat[/i] was chasing the mailman!",
      :italics],
  "Underline"=>
    [/\[u(:.+)?\](.*?)\[\/u\1?\]/mi,
      "<U><s>[u]</s>\\2<e>[/u]</e></U>",
      "Underline",
      "Use it for [u]important[/u] things or something",
      :underline],
  "Code"=>
    [/\[code(:.+)?\](.*?)\[\/code\1?\]/mi,
      "<CODE><s>[code]</s>\\2<e>[/code]</e></CODE>",
      "Code Text",
      "[code]some code[/code]",
      :code],
  "Size"=>
    [/\[size=(&quot;|&apos;|)(\d*?)\1\](.*?)\[\/size\]/mi,
      "<SIZE size=\"#{SIZE_MAP['\2'.to_i]}\"><s>[size=\\2]</s>\\3<e>[/size]</e></SIZE>",
      "Change text size",
      "[size=5]Here is some larger text[/size]",
      :size],
  "Color"=>
    [/\[color=(&quot;|&apos;|)(\w+|\#\w{6})\1(:.+)?\](.*?)\[\/color\3?\]/mi,
      "<COLOR color=\"\\2\"><s>[color=\\2]</s>\\4<e>[/color]</e></COLOR>",
      "Change text color",
      "[color=red]This is red text[/color]",
      :color],
  "List Item"=>
    [/\[\*(:[^\[]+)?\]([^(\[|\<)]+)/mi,
      "<LI><s>[*]</s>\\2</LI>",
      "List item (alternative)",
      "[*]list item",
      :listitem],
  "Unordered list (alternative)"=>
    [/\[list(:.*)?\]((?:(?!\[list(:.*)?\]).)*)\[\/list(:.)?\1?\]/mi,
      "<LIST><s>[list]</s>\\2<e>[/list]</e></LIST>",
      "Unordered list item",
      "[list][*]item 1[*] item2[/list]",
      :list],
  "Ordered list (numerical)"=>
    [/\[list=1(:.*)?\](.+)\[\/list(:.)?\1?\]/mi,
      "<LIST type=\"decimal\"><s>[list=1]</s>\\2<e>[/list]</e></LIST>",
      "Ordered list numerically",
      "[list=1][*]item 1[*] item2[/list]",
      :list],
  "Ordered list (lowercase alphabetical)"=>
    [/\[list=a(:.*)?\](.+)\[\/list(:.)?\1?\]/mi,
      "<LIST type=\"lower-alpha\"><s>[list=a]</s>\\2<e>[/list]</e></LIST>",
      "Ordered list alphabetically",
      "[list=a][*]item 1[*] item2[/list]",
      :list],
  "Ordered list (uppercase alphabetical)"=>
    [/\[list=a(:.*)?\](.+)\[\/list(:.)?\1?\]/mi,
      "<LIST type=\"upper-alpha\"><s>[list=A]</s>\\2<e>[/list]</e></LIST>",
      "Ordered list alphabetically",
      "[list=a][*]item 1[*] item2[/list]",
      :list],
  "Quote"=>
    [/\[quote(:.*)?\](.*?)\[\/quote\]/mi,
      "<QUOTE><s>[quote]</s>\\2<e>[/quote]</e></QUOTE>",
      "Quote",
      "[quote]Now is the time...[/quote]",
      :quote],
  "Link"=>
    [/\[url=(?:&quot;)?(.*?)(?:&quot;)?\](.*?)\[\/url\]/mi,
      "<URL url=\"\\1\"><s>[url]</s>\\2<e>[/url]</e></URL>",
      "Hyperlink to somewhere else",
      "Maybe try looking on [url=http://google.com]Google[/url]?",
      :link],
  "Link (Implied)"=>
    [/\[url\](.*?)\[\/url\]/mi,
      "<URL url=\"\\1\"><s>[url=\\1]</s>\\1<e>[/url]</e></URL>",
      "Hyperlink (implied)",
      "Maybe try looking on [url]http://google.com[/url]",
      :link],
  "Image"=>
    [/\[img(:.+)?\]([^\[\]].*?)\.(png|bmp|jpg|gif|jpeg)\[\/img\1?\]/mi,
      "<IMG src=\"\\2.\\3\" /><s>[img]</s>\\2.\\3<e>[/img]</e>",
      "Display an image",
      "Check out this crazy cat: [img]http://catsweekly.com/crazycat.jpg[/img]",
      :image],
  "YouTube"=>
    [/\[youtube\](.*?)\?v=([\w\d\-]+).*?\[\/youtube\]/mi,
      "<iframe id=\"ytplayer\" type=\"text/html\" width=\"640\" height=\"390\" src=\"//youtube.com/embed/\\2\" frameborder=\"0\"></iframe>",
      "Display a video from YouTube.com",
      "[youtube]http://youtube.com/watch?v=E4Fbk52Mk1w[/youtube]",
      :video],
  "YouTube (Alternative)"=>
    [/\[youtube\](.*?)\/v\/([\w\d\-]+)\[\/youtube\]/mi,
      "<iframe id=\"ytplayer\" type=\"text/html\" width=\"640\" height=\"390\" src=\"//youtube.com/embed/\\2\" frameborder=\"0\"></iframe>",
      "Display a video from YouTube.com (alternative format)",
      "[youtube]http://youtube.com/watch/v/E4Fbk52Mk1w[/youtube]",
      :video],
  "Vimeo"=>
    [/\[vimeo\](.*?)\/(\d+)\[\/vimeo\]/mi,
      "<iframe src=\"//player.vimeo.com/video/\\2\" width=\"640\" height=\"390\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
      "Display a video from Vimeo",
      "[vimeo]http://www.vimeo.com/3485239[/vimeo]",
      :video],
  "Google Video"=>
    [/\[gvideo\](.*?)\?docid=([-]{0,1}\d+).*\[\/gvideo\]/mi,
      "<embed style=\"width:400px; height:326px;\" id=\"VideoPlayback\" type=\"application/x-shockwave-flash\" src=\"http://video.google.com/googleplayer.swf?docId=\\2\" flashvars=\"\"> </embed>",
      "Display a video from Google Video",
      "[gvideo]http://video.google.com/videoplay?docid=-2200109535941088987[/gvideo]",
      :video],
  "Email"=>
    [/\[email[^:=]?\](((?!\[\/email\]).)*)\[\/email\]/mi,
      "<a href=\"mailto:\\1\">\\1</a>",
      "Link to email address",
      "[email]wadus@wadus.com[/email]",
      :email],
  "Email (alternative)"=>
    [/\[email[:=]([^\]]+)\](((?!\[\/email\]).)*)(\[\/email\1?\])?/mi,
      "<a href=\"mailto:\\1\">\\2</a>",
      "Link to email address",
      "[email:wadus@wadus.com]Email Me[/email]",
      :email],
  "Align"=>
    [/\[align=(.*?)\](.*?)\[\/align\]/mi,
      "<span class=\"bb-ruby_align_\\1\" style=\"float:\\1;\">\\2</span>",
      "Align this object using float",
      "Here's a wrapped image: [align=right][img]image.png[/img][/align]",
      :align],
  "Left"=>    
    [/\[left(:.+)?\](.*?)\[\/left\1?\]/mi,
      "<div style=\"text-align: left;\">\\2</div>",
      "Aligns contents along the left side",
      "[left]Left-aligned content[/left]",
      :left],
  "Center"=>
    [/\[center(:.+)?\](.*?)\[\/center\1?\]/mi,
      "<div style=\"text-align: center;\">\\2</div>",
      "Aligns contents on the center",
      "[center]Centered content[/center]",
      :center],
  "Right"=>
    [/\[right(:.+)?\](.*?)\[\/right\1?\]/mi,
      "<div style=\"text-align: right;\">\\2</div>",
      "Aligns contents along the right side",
      "[right]Right-aligned content[/right]",
      :right],
  "Line break"=>
    [/\[br\]/mi,
      "<br />",
      "Inserts line break tag",
      "One[br]Two[br]Three lines!",
      :br]}
